### ISSUE TITLE
Use a better font

### ISSUE THREAD

**Issue by pixelastic** [Shipow/searchstone#21]
The current font seems to not be correctly loaded

![image](https://cloud.githubusercontent.com/assets/283419/15456136/4f1d15e6-201c-11e6-98f0-43a161d96b8e.png)

![image](https://cloud.githubusercontent.com/assets/283419/15456141/6f8c9f0e-201c-11e6-9553-1c5db116e0a7.png)

**Comment by Shipow** [comment]
updated, back to google font.
