### ISSUE TITLE
French internationalization issue

### ISSUE THREAD

**Issue by pixelastic** [Shipow/searchstone#3]
Some cards have singular/plural i18n notes still embedded in their display:
![image](https://cloud.githubusercontent.com/assets/283419/15273641/d29cbaa6-1aa0-11e6-8fad-069093c1c0fb.png)![image](https://cloud.githubusercontent.com/assets/283419/15273645/d914372e-1aa0-11e6-962c-2620760a686e.png)![image](https://cloud.githubusercontent.com/assets/283419/15273647/e2948a1a-1aa0-11e6-8bf1-eceb927916b7.png)![image](https://cloud.githubusercontent.com/assets/283419/15273649/eb26c0da-1aa0-11e6-9a93-c97d32a8bdc4.png)![image](https://cloud.githubusercontent.com/assets/283419/15273658/2e0ea6d8-1aa1-11e6-9a02-d2e3042021ff.png)![image](https://cloud.githubusercontent.com/assets/283419/15273663/50b7cbec-1aa1-11e6-9d54-91f4361fd14a.png)![image](https://cloud.githubusercontent.com/assets/283419/15273665/5b2dd9cc-1aa1-11e6-927a-656db1ce6013.png)![image](https://cloud.githubusercontent.com/assets/283419/15273677/a8153820-1aa1-11e6-9944-d5c65d306320.png)![image](https://cloud.githubusercontent.com/assets/283419/15273678/ace32880-1aa1-11e6-950c-523386242ac0.png)![image](https://cloud.githubusercontent.com/assets/283419/15273679/b1572196-1aa1-11e6-9c92-b5e5bf0040fb.png)![image](https://cloud.githubusercontent.com/assets/283419/15273681/b6f2d078-1aa1-11e6-8e01-5b52818f8bf3.png)![image](https://cloud.githubusercontent.com/assets/283419/15273682/bb2efa18-1aa1-11e6-91b8-f73b5eb0e61c.png)![image](https://cloud.githubusercontent.com/assets/283419/15273693/e2128438-1aa1-11e6-9251-4954f565b855.png)![image](https://cloud.githubusercontent.com/assets/283419/15273702/0f3b2104-1aa2-11e6-815d-b36149da76d7.png)![image](https://cloud.githubusercontent.com/assets/283419/15273703/13dd8990-1aa2-11e6-976e-b14b9381fd47.png)![image](https://cloud.githubusercontent.com/assets/283419/15273713/55f5d616-1aa2-11e6-8a5d-fa335a6ed9a5.png)![image](https://cloud.githubusercontent.com/assets/283419/15273725/8da82e74-1aa2-11e6-87bc-bed49fd3312f.png)![image](https://cloud.githubusercontent.com/assets/283419/15273728/9bb9d454-1aa2-11e6-9720-b3cc334db4cf.png)![image](https://cloud.githubusercontent.com/assets/283419/15273729/9f9c6ca8-1aa2-11e6-84c0-8513e7c769f0.png)![image](https://cloud.githubusercontent.com/assets/283419/15273731/a8a105d4-1aa2-11e6-9d74-2dda1981994c.png)![image](https://cloud.githubusercontent.com/assets/283419/15273732/af58dde8-1aa2-11e6-8045-85c63af283ac.png)![image](https://cloud.githubusercontent.com/assets/283419/15273757/e9f4ef46-1aa2-11e6-8186-7cffb369ca16.png)![image](https://cloud.githubusercontent.com/assets/283419/15273759/f09d861e-1aa2-11e6-952f-af789033ed17.png)![image](https://cloud.githubusercontent.com/assets/283419/15273784/75ddf282-1aa3-11e6-8e67-8bc4092d288f.png)![image](https://cloud.githubusercontent.com/assets/283419/15273788/92982f1e-1aa3-11e6-922a-26e7caf1c630.png)![image](https://cloud.githubusercontent.com/assets/283419/15273809/0a97da1e-1aa4-11e6-9475-2fa44017cfba.png)![image](https://cloud.githubusercontent.com/assets/283419/15273813/1ff5aa8a-1aa4-11e6-9305-ee9f7fcf26a7.png)![image](https://cloud.githubusercontent.com/assets/283419/15273818/3f85b2f0-1aa4-11e6-9414-b87071581420.png)![image](https://cloud.githubusercontent.com/assets/283419/15273819/43573d36-1aa4-11e6-9651-b4e44757c81e.png)![image](https://cloud.githubusercontent.com/assets/283419/15274150/6cc70e50-1aac-11e6-937b-0aedb14b63f6.png)![image](https://cloud.githubusercontent.com/assets/283419/15274152/7acc60a4-1aac-11e6-9ceb-25f210eb15ff.png)![image](https://cloud.githubusercontent.com/assets/283419/15274173/c87b70c4-1aac-11e6-8798-c6d5679706c0.png)![image](https://cloud.githubusercontent.com/assets/283419/15274182/dd713216-1aac-11e6-8848-7e94e75e0639.png)![image](https://cloud.githubusercontent.com/assets/283419/15274184/ea67f18a-1aac-11e6-8f54-feb9865a6d2e.png)![image](https://cloud.githubusercontent.com/assets/283419/15274193/fa649eee-1aac-11e6-8787-f9831792258b.png)![image](https://cloud.githubusercontent.com/assets/283419/15274196/0603b244-1aad-11e6-850e-2291813202e7.png)![image](https://cloud.githubusercontent.com/assets/283419/15274200/0b5cf3b8-1aad-11e6-91f3-08c64418d8b8.png)![image](https://cloud.githubusercontent.com/assets/283419/15274205/1ecc3f4e-1aad-11e6-91fe-eac70b7ed01e.png)![image](https://cloud.githubusercontent.com/assets/283419/15274218/5c6b8c7e-1aad-11e6-9ccc-4422627f98e1.png)![image](https://cloud.githubusercontent.com/assets/283419/15274220/61e18e2e-1aad-11e6-9890-e02a59559390.png)![image](https://cloud.githubusercontent.com/assets/283419/15274223/761f333c-1aad-11e6-94ae-3b1056deebe7.png)![image](https://cloud.githubusercontent.com/assets/283419/15274228/a3e4018a-1aad-11e6-873a-4bd198b4a405.png)![image](https://cloud.githubusercontent.com/assets/283419/15274234/bb949c04-1aad-11e6-92c9-a9058fb89955.png)![image](https://cloud.githubusercontent.com/assets/283419/15274235/c0e12772-1aad-11e6-8b8c-2415fd852440.png)![image](https://cloud.githubusercontent.com/assets/283419/15274239/c6c425cc-1aad-11e6-8005-fb21349657b2.png)![image](https://cloud.githubusercontent.com/assets/283419/15274246/e35992d0-1aad-11e6-8f69-4ff28ab481e6.png)![image](https://cloud.githubusercontent.com/assets/283419/15274263/44e0c69a-1aae-11e6-9ad2-7424d2647600.png)![image](https://cloud.githubusercontent.com/assets/283419/15274267/596f53ce-1aae-11e6-94bd-47569575b830.png)![image](https://cloud.githubusercontent.com/assets/283419/15274280/94109cd6-1aae-11e6-84c0-d8650abaa805.png)![image](https://cloud.githubusercontent.com/assets/283419/15274324/5a3fa56e-1aaf-11e6-830d-238d09baa661.png)![image](https://cloud.githubusercontent.com/assets/283419/15274328/6c66e4c8-1aaf-11e6-8b11-ba2b8929c0ca.png)![image](https://cloud.githubusercontent.com/assets/283419/15274339/a9b4eb68-1aaf-11e6-9a54-9d6d66ef2b18.png)![image](https://cloud.githubusercontent.com/assets/283419/15274351/cf02a00e-1aaf-11e6-8235-686e275f0eeb.png)![image](https://cloud.githubusercontent.com/assets/283419/15274355/e239bd24-1aaf-11e6-98a4-e05ca7242149.png)![image](https://cloud.githubusercontent.com/assets/283419/15274357/e66664ce-1aaf-11e6-8473-011abb6172e5.png)![image](https://cloud.githubusercontent.com/assets/283419/15274365/0b4dd2e0-1ab0-11e6-991b-55dfc3d1948c.png)![image](https://cloud.githubusercontent.com/assets/283419/15274372/2ec33c60-1ab0-11e6-979a-48ee9adbe69f.png)![image](https://cloud.githubusercontent.com/assets/283419/15274382/653f44f0-1ab0-11e6-908b-17652145b88e.png)![image](https://cloud.githubusercontent.com/assets/283419/15274384/6b1e4cd6-1ab0-11e6-9783-f0a3e8a9f3cf.png)![image](https://cloud.githubusercontent.com/assets/283419/15274386/72400892-1ab0-11e6-9261-a8af947e53a5.png)![image](https://cloud.githubusercontent.com/assets/283419/15274387/77209cf0-1ab0-11e6-894d-85cb59f9ac36.png)![image](https://cloud.githubusercontent.com/assets/283419/15274388/7afa5258-1ab0-11e6-8536-dc79f0d0efde.png)![image](https://cloud.githubusercontent.com/assets/283419/15274389/7ea06082-1ab0-11e6-8715-1c68e77e57c9.png)![image](https://cloud.githubusercontent.com/assets/283419/15274392/85ed9314-1ab0-11e6-82cd-c0c6784ebfaf.png)![image](https://cloud.githubusercontent.com/assets/283419/15274397/8fbf66a6-1ab0-11e6-9c66-9240b5f7d257.png)![image](https://cloud.githubusercontent.com/assets/283419/15274398/92073006-1ab0-11e6-94e2-261963772b2c.png)![image](https://cloud.githubusercontent.com/assets/283419/15274399/95404b18-1ab0-11e6-94e6-4f17788a5c2c.png)![image](https://cloud.githubusercontent.com/assets/283419/15274403/af059e72-1ab0-11e6-82e2-6eaa0f365a54.png)![image](https://cloud.githubusercontent.com/assets/283419/15274404/b283856e-1ab0-11e6-979c-1e53ae72f531.png)![image](https://cloud.githubusercontent.com/assets/283419/15274411/ccca3f80-1ab0-11e6-89d1-9b99e3355666.png)![image](https://cloud.githubusercontent.com/assets/283419/15274412/d321053a-1ab0-11e6-93c7-a82cb69a6eca.png)

**Comment by Shipow** [comment]
pluralRegex = /(\d+)(.+?)|4((.+?),(.+?))/g, #

**Comment by Shipow** [comment]
almost! https://www.dropbox.com/s/qua4kcpvq8936j7/Screenshot%202016-06-01%2011.59.07.png?dl=0
:)

**Comment by pixelastic** [comment]
Ok, that's weird. I'll have another look.

**Comment by Shipow** [comment]
GG
