### ISSUE TITLE
Fails to start if the browser language isn't in the pre-programmed list of accepted languages

### ISSUE THREAD

**Issue by sbrandwoo** [Shipow/searchstone#32]

**Comment by sbrandwoo** [comment]
My browser language is en-GB, using Chrome and Firefox on Linux. When SearchStone tries to start up I get this error:

`Uncaught ReferenceError: navlang is not defined`

This seems to be caused in the init code when the language isn't known and it runs the invalid "navlang" code.

(Sorry for the empty comment.. I hit enter too soon when making the issue and GitHub won't let me remove it)

**Comment by Shipow** [comment]
I tried something, let me now if it's fixed :)

**Comment by sbrandwoo** [comment]
Yep, that fixed it, thanks!
