### ISSUE TITLE
Any plan to add the ONiK cards?

### ISSUE THREAD

**Issue by sebastientromp** [Shipow/searchstone#33]
It's a cool search engine, so would have loved to be able to use it with the latest cards

**Comment by Shipow** [comment]
Yeah! I just went back from holiday, I get some work to catch up with but I'll definitely update this project! cheers

**Comment by sebastientromp** [comment]
Awesome, thanks for the hard work!

**Comment by Shipow** [comment]
done! there are probably few bugs, please report :p

**Comment by sebastientromp** [comment]
Awesome, you rule! :D

**Comment by sebastientromp** [comment]
PS: I think the official acronym for Karazhan is just KAR instead of KARA (at least that's how the card ids are prefixed)
