### ISSUE TITLE
Missing card type: bloodreaver Guldan and other DK heroes and other cards

### ISSUE THREAD

**Issue by martinbonnin** [Shipow/searchstone#45]

**Comment by martinbonnin** [comment]
Missing cards:

• bloodreaver Guldan and other DK heroes

• Eviscerate
• Ogre Magi
• Backroom Bouncer
• Tracking
• Direhorn Hatchling
• Arcanologist

**Comment by Shipow** [comment]
Thanks for reporting this.

**Comment by Shipow** [comment]
added heroes from Frozen Thrones

and other cards are back!

thanks!
