### ISSUE TITLE
Ironforge rifleman wrong graphic

### ISSUE THREAD

**Issue by Pumone** [Shipow/searchstone#55]
Hi there, I noticed the card "ironforge rifleman" has the wrong image as "stormwind champion".
Can you fix it?

Thank you and sorry for my bad english.

**Comment by Shipow** [comment]
hey Pumone, I'll have a look, thanks for noticing it !!!

**Comment by Shipow** [comment]
![image](https://user-images.githubusercontent.com/976175/44621876-7f668080-a8ae-11e8-87b1-2206cb3dcbf2.png)
Looks like I got the good one, what language did you used?

**Comment by Pumone** [comment]
I'm using italian language, here the screenshot.


      Da: Kevin Granger <notifications@github.com>
 A: Shipow/searchstone <searchstone@noreply.github.com> 
Cc: Pumone <pumone@yahoo.it>; Author <author@noreply.github.com>
 Inviato: Sabato 25 Agosto 2018 21:33
 Oggetto: Re: [Shipow/searchstone] Ironforge rifleman wrong graphic (#55)
   

Looks like I got the good one, what language did you used?—
