### ISSUE TITLE
Too many bolded words

### ISSUE THREAD

**Issue by pixelastic** [Shipow/searchstone#9]
On some cards, some words are bolded while they should not be.

_edit_: Seems like it is always the `découvre` word that is bolded. Maybe it is normal after all?

![image](https://cloud.githubusercontent.com/assets/283419/15273724/87aa2eaa-1aa2-11e6-9182-9f98681a35c5.png)
![image](https://cloud.githubusercontent.com/assets/283419/15274210/39297d02-1aad-11e6-92d9-bdbdfb92d30b.png)
![image](https://cloud.githubusercontent.com/assets/283419/15274222/6cddb6e0-1aad-11e6-8960-d4b718b87155.png)
![image](https://cloud.githubusercontent.com/assets/283419/15274225/8625a3d8-1aad-11e6-8dd1-52b4edd8d82f.png)

**Comment by Shipow** [comment]
seems normal
